FROM node:18

# Install bun
RUN npm install -g bun

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json .

RUN bun install

# Copy app source
COPY . .

# Generate prisma
RUN bunx prisma generate

WORKDIR /app/utils

ENTRYPOINT ["bun", "run", "idfmFetch.ts"]
